//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlubSportowy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Druzyny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Druzyny()
        {
            this.HarmonogramObiektow = new HashSet<HarmonogramObiektow>();
            this.Mecze = new HashSet<Mecze>();
            this.Treningi = new HashSet<Treningi>();
            this.Zawodnicy = new HashSet<Zawodnicy>();
        }
    
        public int DruzynaId { get; set; }
        public string Nazwa { get; set; }
        public string Kategoria { get; set; }
        public Nullable<int> TrenerId { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyDodal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoWykasowal { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Trenerzy Trenerzy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HarmonogramObiektow> HarmonogramObiektow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mecze> Mecze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treningi> Treningi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zawodnicy> Zawodnicy { get; set; }
    }
}
