//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlubSportowy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontuzje
    {
        public int KontuzjaId { get; set; }
        public Nullable<int> ZawodnikId { get; set; }
        public string TypKontuzji { get; set; }
        public Nullable<System.DateTime> DataZdarzenia { get; set; }
        public Nullable<System.DateTime> PrzewidywanyPowrot { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyDodal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoWykasowal { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Zawodnicy Zawodnicy { get; set; }
    }
}
