//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlubSportowy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mecze()
        {
            this.StatystykiMeczowe = new HashSet<StatystykiMeczowe>();
        }
    
        public int MeczId { get; set; }
        public Nullable<int> DruzynaId { get; set; }
        public string Przeciwnik { get; set; }
        public Nullable<System.DateTime> DataMeczu { get; set; }
        public string Wynik { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyDodal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoWykasowal { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Druzyny Druzyny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatystykiMeczowe> StatystykiMeczowe { get; set; }
    }
}
