//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlubSportowy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KlubSportowyEntities : DbContext
    {
        public KlubSportowyEntities()
            : base("name=KlubSportowyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Druzyny> Druzyny { get; set; }
        public virtual DbSet<Frekwencja> Frekwencja { get; set; }
        public virtual DbSet<HarmonogramObiektow> HarmonogramObiektow { get; set; }
        public virtual DbSet<Kontuzje> Kontuzje { get; set; }
        public virtual DbSet<LogiOperacji> LogiOperacji { get; set; }
        public virtual DbSet<Magazyny> Magazyny { get; set; }
        public virtual DbSet<Mecze> Mecze { get; set; }
        public virtual DbSet<Platnosci> Platnosci { get; set; }
        public virtual DbSet<Rodzice> Rodzice { get; set; }
        public virtual DbSet<Sprzet> Sprzet { get; set; }
        public virtual DbSet<StatystykiMeczowe> StatystykiMeczowe { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trenerzy> Trenerzy { get; set; }
        public virtual DbSet<Treningi> Treningi { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
        public virtual DbSet<WypozyczeniaSprzetu> WypozyczeniaSprzetu { get; set; }
        public virtual DbSet<Zawodnicy> Zawodnicy { get; set; }
    }
}
