//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlubSportowy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawodnicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zawodnicy()
        {
            this.Frekwencja = new HashSet<Frekwencja>();
            this.Kontuzje = new HashSet<Kontuzje>();
            this.Platnosci = new HashSet<Platnosci>();
            this.Rodzice = new HashSet<Rodzice>();
            this.StatystykiMeczowe = new HashSet<StatystykiMeczowe>();
            this.WypozyczeniaSprzetu = new HashSet<WypozyczeniaSprzetu>();
        }
    
        public int ZawodnikId { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<System.DateTime> DataUrodzenia { get; set; }
        public string Pozycja { get; set; }
        public Nullable<int> DruzynaId { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public string KtoDodal { get; set; }
        public Nullable<System.DateTime> KiedyDodal { get; set; }
        public string KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public string KtoWykasowal { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Druzyny Druzyny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Frekwencja> Frekwencja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontuzje> Kontuzje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platnosci> Platnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rodzice> Rodzice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatystykiMeczowe> StatystykiMeczowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypozyczeniaSprzetu> WypozyczeniaSprzetu { get; set; }
    }
}
